[package]
name = "owf-core"
edition.workspace = true
version.workspace = true

[dependencies]
anyhow.workspace = true
thiserror.workspace = true
serde.workspace = true
serde_json.workspace = true
toml.workspace = true
tracing.workspace = true
dirs.workspace = true
regex.workspace = true
ureq.workspace = true
sha2 = "0.11"
tar = "0.4"
bzip2 = "0.5"
sherpa-onnx = "1.13.6"
hound = "3.5"
whatlang = "0.18"
cpal = "0.18"
rubato = "5.0"
notify-rust = "4.18"

[dev-dependencies]
hound = "3.5"
httpmock = "0.8"
